apiVersion: batch/v1
kind: Job
metadata:
  generateName: mp12-free
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: mp12-free
        image: derekshen/mp12:v1
        env:
        - name: DATASET
          value: "mnist"
        - name: TYPE
          value: "ff"
        resources:
          limits:
            cpu: "900m"
      restartPolicy: Never
  backoffLimit: 4